[workspace]
resolver = "2"
members = [
    "crates/noxssh-core",
    "crates/noxssh-client",
    "crates/noxssh-server",
    "crates/noxssh-shell",
    "crates/noxssh-cli",
    "crates/noxsshd",
    "crates/noxssh",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["Argenox Technologies LLC"]
license = "GPL-2.0-only OR LicenseRef-Argenox-Commercial-License"
description = "Lightweight SSH-2 client and server in Rust using NoxTLS Library"
readme = "README.md"
documentation = "https://docs.rs/noxssh"
homepage = "https://noxtls.com"
repository = "https://github.com/argenox/noxssh-rs"
keywords = ["ssh", "noxtls", "crypto", "client", "server"]
categories = ["command-line-utilities", "cryptography", "network-programming"]
rust-version = "1.75"

[workspace.dependencies]
noxtls-crypto = "0.1.3"
noxtls-x509 = "0.1.3"
noxssh-core = { path = "crates/noxssh-core", version = "0.2.0" }
noxssh-client = { path = "crates/noxssh-client", version = "0.2.0" }
noxssh-server = { path = "crates/noxssh-server", version = "0.2.0" }
noxssh-shell = { path = "crates/noxssh-shell", version = "0.2.0" }
crossterm = "0.28"
rpassword = "7"
