[package]
name = "noxssh"
version = "0.1.11"
edition = "2021"
build = "build.rs"
authors = ["Argenox Technologies LLC"]
license = "GPL-2.0-only OR LicenseRef-Argenox-Commercial-License"
description = "Lightweight SSH-2 client in Rust using NoxTLS Library"
readme = "README.md"
documentation = "https://docs.rs/noxssh"
homepage = "https://noxtls.com"
repository = "https://github.com/argenox/noxssh-rs"
keywords = ["ssh", "noxtls", "crypto", "client"]
categories = ["command-line-utilities", "cryptography", "network-programming"]
rust-version = "1.75"

[dependencies]
rpassword = "7"
crossterm = "0.28"
noxtls-crypto = "0.1.3"
noxtls-x509 = "0.1.3"
