[package]
name = "noxssh-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "SSH-2 server for noxssh"
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
noxssh-core.workspace = true
