[package]
name = "noxssh-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "SSH-2 client for noxssh"
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
noxssh-core = { workspace = true, features = ["cli"] }
noxtls-crypto.workspace = true
noxtls-x509.workspace = true

[dependencies.rpassword]
workspace = true
optional = true

[features]
default = []
cli = ["rpassword"]
