[package]
name = "noxsshd"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "noxssh server daemon"
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "noxsshd"
path = "src/main.rs"

[dependencies]
noxssh-core.workspace = true
noxssh-server.workspace = true
